check_versions_for: ['ruby', 'rails', 'rake', 'bundler', 'capistrano', 'capistrano_ruby']
rails_dependency:
  '3.0':
    ruby: '>= 1.8.7'
    bundler: '>= 1.0, < 2.0'
  '4.0':
    ruby:  '>= 1.9.3'
    bundler: '>= 1.3.0, < 2.0'
  '5.0':
    ruby: '>= 2.2.2'
    bundler: '>= 1.3.0'
  '6.0':
    ruby: ">= 2.5.0"
    bundler: '>= 1.3.0'
