version: '3'

services:
  iris:
    build:
      context: .
      dockerfile: compose/Dockerfile
    command: bundle exec puma -C config/puma.rb
    env_file: .env
    environment:
      RACK_ENV: development
    volumes:
      - ./:/iris
    ports:
      - "${IRIS_APP_PORT}:${IRIS_APP_PORT}"
